apiVersion: v1
kind: Service
metadata:
  name: static-site-service
spec:
  type: NodePort
  selector:
    app: static-site
  ports:
    - protocol: TCP
      port: 80        # The port exposing the service internally
      targetPort: 80  # The containerPort where Nginx is listening
      nodePort: 30080 # The port to access the website via your node IP
